# Site settings
title: A Collection of Thoughts
description: >
    A Collection of Thoughts
author: Vitus Ortner
email: vitusortner.dev@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vitus.dev" # the base hostname & protocol for your site
twitter_username: vitusortner
github_username:  vitusortner

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
plugins:
    - jekyll-seo-tag    
